name: Deploy to Azure VMs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to Azure VM using Username and Password
        env:
          VM_HOST: ${{ secrets.VM_HOST }}         
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
          VM_PASSWORD: ${{ secrets.VM_PASSWORD }} 
        run: |
          sshpass -p "$VM_PASSWORD" ssh -o StrictHostKeyChecking=no -t "$VM_USERNAME@$VM_HOST" "
            cd azure-vm-cicd &&
            git pull &&
            sudo docker-compose up --build -d
          "
